version: '2.7'

services:
  app:
    container_name: proyecto-distribuidos
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      # - node_modules
    ports:
      - 3001:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  